### ISSUE TITLE
BUG：The resource could not be loaded

### ISSUE THREAD

**Issue by PeiyueFu** [mudkipme/MoeMemos#152]
The Memos server only me use it,so I set up server on X86 in the Local internet.In the normal local internet，I can use it。
   I don't have public internet Ip，so if I want to use the （IOS app）Memos，I need to use **NAT Traversal** （**Tailscale**：basic of WireGuard，Mesh ）
   In the past year，On **IOS 15.6 Iphone XR and Iphone SE2** can connet to the server out side my house by use Tailscale.
   However，now updata to **IOS 17.1** both two phones could't not sign in App Memos.And it display this words** The resource could not be loaded**
![image](https://github.com/mudkipme/MoeMemos/assets/156740631/3d9ba92d-b5f8-444b-80c3-e43e8629245b)

In Memos Server 's web，I see someone put up this same bug.
The developer asked him to comment here，but I don't see any  message.
![image](https://github.com/mudkipme/MoeMemos/assets/156740631/3008c1cd-1bb8-40e6-96b0-c1b2e833e39e)

Based on my only little development experience，I think it's the security policy of IOS17.0 forbid HTTP in some API.
Just allow HTTPS. I'm lack of IOS development experience，so my  tried did't work.

Part of use Memos App out side is very important，I can jot down ideas anywhere, anytime.
Hope develor can fix this BUG.
If anyone have way to help me，I wish.

**Comment by PeiyueFu** [comment]
苹果手机在家内网连wifi，用http IPV4连接正常。
在外面用tailscale，以前的ios版本15.6就可以，现在升到16，17就不行了。博客上大多都是说苹果的安全策略是禁止用了HTTP必须要用HTTPS，需要在polit.info里面加入强制使用HTTP的代码。

**Comment by mudkipme** [comment]
Moe Memos for iOS doesn't support plain HTTP connection due to Apple's App Transport Security policy (other than connecting to local network via IP address). While it's possible to adding `Allows Arbitrary Loads` settings in `Info.plist`, it requires justification for exceptions to App Store review according to [the documentation](https://developer.apple.com/documentation/security/preventing_insecure_network_connections), which may likely be rejected by Apple.

As you are using Tailscale, please learn [how to enable HTTPS with `tailscale cert`](https://tailscale.com/kb/1153/enabling-https).
