### ISSUE TITLE
大佬，啥时候能支持0.22么？感谢这么好的客户端。

### ISSUE THREAD

**Issue by netdog2019** [mudkipme/MoeMemos#181]
大佬，啥时候能支持0.22么？感谢这么好的客户端。
不小心升级到了0.22，发现IOS端不支持，不知道大佬啥时有空能更新支持到0.22版，感谢。

**Comment by mudkipme** [comment]
Support for Memos 0.22 (and keep support for previous versions due to many users are not upgraded yet) requires significant changes and will take longer than previous versions.

There is no ETA yet though I hope to finish the development within this month.

In the meantime, using "Add to Home Screen" with Memos' web app is recommended.

**Comment by Mydong** [comment]
Memos officially changed too much.
I'm going to go back to the old version and use it all the time, no more tossing.
0.22 or above, data compatibility is not good!
