### ISSUE TITLE
Can no longer sign in after updating to latest memos server

### ISSUE THREAD

**Issue by oregonpillow** [mudkipme/MoeMemos#89]
When I try and sign in it says "invalid access token". 

Was the last update to backend breaking for this app?

I can login to my server directly in browser with the same credentials and works fine. But In the MoeMemos app now I can't .

**Comment by mudkipme** [comment]
Please try upgrading the app to 1.5.2 or try logging with Open API.

**Comment by oregonpillow** [comment]
Just updated but same problem

![image](https://github.com/mudkipme/MoeMemos/assets/53374403/55638a5b-3afd-4803-b4e4-c0124126ff05)

**Comment by oregonpillow** [comment]
OpenAPI working now 👍🏼. Thanks. Although I don't understand why username/password authentication has stopped working.

**Comment by mudkipme** [comment]
Moe Memos uses `/api/status` to detect the version Memos.

It seems there is an issue fixed by https://github.com/usememos/memos/commit/2033b0c8fa8fe7c759949b7be28b289ca74b122a, which prevent `/api/status` from accessible in some conditions. As a result, it's recommended to only log in via Open API with Memos 0.13.2.

The future version of Memos will move lots of API to `/api/v1` prefix, including `/api/v1/status`, that will require an update for Moe Memos.

**Comment by mudkipme** [comment]
Memos 0.13.2 had an bug which prevents Moe Memos from logging-in after the session expires.
It is fixed in Memos 0.14.0 and please upgrade to Moe Memos 1.5.3 to support the latest server version.
